name = "SignalIndices"
uuid = "18f53e89-494d-4131-905c-653e8ada6cd8"
authors = ["Galen Lynch <galen@galenlynch.com>"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
IterTools = "1"
julia = "1.10"
